-- Explore all objects in the database
select * from INFORMATION_SCHEMA.TABLES

-- Explore all columns in the database
select * from INFORMATION_SCHEMA.COLUMNS
Where TABLE_NAME = 'dim_customers'


-- Explore All Countries our customers come from.
select distinct country from gold.dim_customers

-- Explore All Categories "The major Divisions"
select distinct category, subcategory, product_name from gold.dim_products
order by 1,2,3

-- Find the date of the first and last order
select 
min(order_date) first_order_date,
MAX(order_date) last_order_date,
DATEDIFF(MONTH,MIN(order_date),max(order_date)) order_range_months
from gold.fact_sales

-- Find the youngest and the oldest customer
select 
min(birthdate) as oldest_birthday,
DATEDIFF(YEAR,MIN(birthdate),GETDATE()) as oldest_age,
MAX(birthdate) as youngest_birthday,
DATEDIFF(YEAR,Max(birthdate),GETDATE()) as youngest_age
from gold.dim_customers

-- Find the Total Sales
select SUM(sales_amount) as total_sales from gold.fact_sales

-- Find how many items are sold
select SUM(quantity) as QTY from gold.fact_sales

-- Find the average selling price
select avg(price) as pr from gold.fact_sales

-- Find the Total number of Orders
select COUNT(order_number) as o from gold.fact_sales
select COUNT(distinct order_number) as o from gold.fact_sales

-- Find the total number of products
select COUNT(product_key) as total_products from gold.dim_products
select COUNT(distinct product_key) as total_products from gold.dim_products

-- Find the total number of customers
select count(customer_number) as total_customers from gold.dim_customers

-- Find the total number of customers that has placed an order
select count(distinct customer_key) as total_customers from gold.fact_sales

-- Generate a Report that shows all key metrics of the business

select 'Total Sales' as measure_name, SUM(sales_amount) as measure_value from gold.fact_sales
Union All
select 'Total Quantity' as measure_name, SUM(quantity) as measure_value from gold.fact_sales
Union All
select 'Average Price', Avg(price) as pr from gold.fact_sales
Union All
select 'Total Nr. Orders' ,COUNT(distinct order_number) as o from gold.fact_sales
Union All
select 'Total Nr.Products',COUNT(product_key) as total_products from gold.dim_products
Union All
select 'Total Nr.Customers', count(distinct customer_key) as total_customers from gold.fact_sales

-- Find total customers by countries
Select 
country,
COUNT(customer_key) AS total_customers
from gold.dim_customers
group by country
order by total_customers desc

-- Find total customers by gender
Select 
gender,
COUNT(customer_key) AS total_customers
from gold.dim_customers
group by gender
order by total_customers desc

-- Find total products by category
Select 
category,
COUNT(product_key) AS total_products
from gold.dim_products
group by category
order by total_products desc

-- What is the average costs in each category?
Select 
category,
Avg(cost) AS Avg_cost
from gold.dim_products
group by category
order by Avg_cost desc

-- What is the total revenue generated for each category?
Select
p.category,
sum(f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.category
order by total_revenue desc

-- Find total revenue is generated by each customer
select
c.customer_key,
c.first_name,
c.last_name,
Sum(f.sales_amount) as total_revenue
from gold.fact_sales f
Left join gold.dim_customers c
on c.customer_key = f.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc

-- What is the distribution of sold items across countries?

select
c.country,
Sum(f.quantity) as total_sold_items
from gold.fact_sales f
Left join gold.dim_customers c
on c.customer_key = f.customer_key
group by 
c.country
order by total_sold_items desc

-- Which 5 Products generate the highest revenue?
select top 5
p.product_name,
Sum(f.sales_amount) total_revenue
from gold.fact_sales f
Left join gold.dim_products p
on p.product_key = f.product_key
group by 
p.product_name
order by total_revenue desc

-- What are the 5 worst-performing products in terms of sales?
select top 5
p.product_name,
Sum(f.sales_amount) total_revenue
from gold.fact_sales f
Left join gold.dim_products p
on p.product_key = f.product_key
group by 
p.product_name
order by total_revenue 

-- Find the top 10 customers who have generated the highest revenue
select top 10
c.customer_key,
c.first_name,
c.last_name,
Sum(f.sales_amount) as total_revenue
from gold.fact_sales f
Left join gold.dim_customers c
on c.customer_key = f.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc

-- The 3 customers with the fewest orders placed
select top 3
c.customer_key,
c.first_name,
c.last_name,
Count(Distinct order_number) as total_orders
from gold.fact_sales f
Left join gold.dim_customers c
on c.customer_key = f.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_orders
